# Generated by Django 5.0.4 on 2025-10-24 17:30
from datetime import timedelta

from django.db import migrations

def modify(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    DeletedOrder = apps.get_model('main_app', 'DeletedOrder')

    for order in Order.objects.all():
        if order.status == Order.CANCELLED:
            order.delete()
            return
        if order.status == Order.PENDING:
            order.delivery = order.delivery + timedelta(days=3)
        elif order.status == Order.COMPLETED:
            order.warranty = "24 months"
        order.save()

def reverse_modify(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(modify, reverse_code=reverse_modify),
    ]
