# Generated by Django 5.0.4 on 2026-02-03 18:54

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(validators=[books.validators.BadWordsValidator(['badword1', 'badword2'])]),
        ),
    ]
